---
language: python
services: docker

env:
  global:
    - ROLE_NAME: os
  matrix:
    -
      MOLECULE_DISTRO: centos7
      MOLECULE_PLATFORM_VOLUMES: "\"['/sys/fs/cgroup:/sys/fs/cgroup:ro',]\""
    -
      MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLATFORM_VOLUMES: >
        "['/sys/fs/cgroup:/sys/fs/cgroup:ro',
        '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro',
        '/usr/share/zoneinfo:/usr/share/zoneinfo:ro']"
install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME thuvh.$ROLE_NAME
  - cd thuvh.$ROLE_NAME

script:
  # Run tests.
  - molecule test --parallel --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
