---
- name: refresh os
  apt:
    update_cache: true
    cache_valid_time: 86400
    name: "*"
    state: latest
    autoclean: true
    autoremove: true

- name: install common packages
  apt:
    name:
      - vim
      - git
      - build-essential
      - tmux
      - htop
      - nload
      - sysstat
      - iotop
      - iostat
      - dstat
      - tcptraceroute
      - wget
      - curl
      - dnstop
      - pstree
      - tree
    state: latest
