---
- name: clean yum
  command: yum clean all
  args:
    warn: false

- name: refresh os
  yum:
    name: '*'
    state: latest

- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install common packages
  yum:
    name: '{{ os_common_packages.yum }}'
    state: latest
