---
- name: refresh os
  apt:
    update_cache: true
    cache_valid_time: 86400
    name: "*"
    state: latest
    autoclean: true
    autoremove: true

- name: install common packages
  apt:
    name: '{{ os_common_packages.apt }}'
    state: latest
