---
- name: refresh os
  yum:
    name: '*'
    update_cache: true
    state: latest

- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install common packages
  yum:
    name: '{{ os_common_packages.yum }}'
    state: latest
